# Use the official Python 3.10 image as base
FROM python:3.10

# Set environment variables (optional)
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file first to leverage Docker cache
COPY external/watermarking/requirements_cpu.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements_cpu.txt

# Copy the rest of the application code into the container
COPY external/watermarking .

# Set the default command to run when the container starts
CMD ["python3", "tests/benchmarks/watermarking/llm_server.py", "--cpu_debug"]
