# ruff: noqa: F401

from complai.tasks.aime_2025 import aime_2025
from complai.tasks.arc_challenge import arc_challenge
from complai.tasks.bbq import bbq
from complai.tasks.bigbench_calibration import bigbench_calibration
from complai.tasks.bold import bold
from complai.tasks.boolq_contrast import boolq_contrast
from complai.tasks.decoding_trust import decoding_trust
from complai.tasks.fairllm import fairllm
from complai.tasks.forecast_consistency import forecast_consistency
from complai.tasks.hellaswag import hellaswag
from complai.tasks.hle import hle
from complai.tasks.human_deception import human_deception
from complai.tasks.humaneval import humaneval
from complai.tasks.imdb_contrast import imdb_contrast
from complai.tasks.include import include
from complai.tasks.instruction_goal_hijacking import instruction_goal_hijacking
from complai.tasks.livebench_coding import livebench_coding
from complai.tasks.llm_rules import llm_rules
from complai.tasks.mmlu_pro import mmlu_pro
from complai.tasks.mmlu_pro_robustness import mmlu_pro_robustness
from complai.tasks.realtoxicityprompts import realtoxicityprompts
from complai.tasks.self_check_consistency import self_check_consistency
from complai.tasks.swe_bench_verified import swe_bench_verified
from complai.tasks.triviaqa_calibration import triviaqa_calibration
from complai.tasks.truthfulqa import truthfulqa
