task: hellaswag_gen
dataset_path: hellaswag
test_split: validation
process_docs: !function hellaswag.process_docs
description: "You are a helpful assistant. For each snippet of text, complete the answer by selecting from the options A,B,C,D. The answer should consist of a single letter option A,B,C,D and no additional text."
doc_to_text: input
doc_to_target: ''
output_type: generate_until
process_results: !function hellaswag.process_results
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
