task: imdb_contrastset
dataset_path: compl-ai/imdb_contrastset
test_split: train
process_docs: !function imdb_contrastset.process_docs
description: You are a helpful assistant. For each snippet of text, predict the Sentiment by selecting from the option 'Positive' or 'Negative'. The answer should be exactly 'Positive' or 'Negative'."
doc_to_text: input
doc_to_target: ''
output_type: generate_until
process_results: !function imdb_contrastset.process_results
metric_list:
  - metric: is_correct
    aggregation: mean
    higher_is_better: true
  - metric: num_invalid
    aggregation: !function imdb_contrastset.sum_aggregation
    higher_is_better: false
